# Generated by Django 4.2.7 on 2023-11-03 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Diagnostics', models.TextField()),
                ('Location', models.CharField(max_length=200)),
                ('Specialization', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Patient_Record',
            fields=[
                ('Record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Created_date', models.DateTimeField(auto_now_add=True)),
                ('Diagnostics', models.TextField()),
                ('Observation', models.TextField()),
                ('Treatments', models.TextField()),
                ('Misc', models.TextField(verbose_name='Miscellaneous')),
                ('Department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_records_app.department')),
                ('Doctor_id', models.ForeignKey(limit_choices_to={'groups__name': 'Doctors'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL, verbose_name='Doctor')),
                ('Patient_id', models.ForeignKey(limit_choices_to={'groups__name': 'Patients'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
            ],
            options={
                'verbose_name_plural': 'Patient Records',
            },
        ),
    ]
